environments:
  dev:
    values:
      - pullPolicy: IfNotPresent

---

repositories:
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts

releases:
- name: {{ .Environment.Name }}-prom-norbac-ubuntu
  namespace: "{{ .Namespace }}"
  chart: prometheus-community/prometheus
  version: 27.11.0
  set:
  - name: rbac.create
    value: false
